services:
  - type: web
    name: cashback-affiliate-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: cashback-postgres
    databaseName: cashback_app
    user: cashback_user
    plan: free
